Retry the usb0 configuration if it fails

diff --git a/carnotzet+whispi-gadget-rpi64/assets/sv/run b/carnotzet+whispi-gadget-rpi64/assets/sv/run
--- a/carnotzet+whispi-gadget-rpi64/assets/sv/run
+++ b/carnotzet+whispi-gadget-rpi64/assets/sv/run
@@ -85,9 +85,23 @@ mount_gadget() {
    # Network
    #########
 
-   ip -6 addr flush dev usb0
-   ip -6 addr add "fd66:66:66::1/64" dev usb0
-   ip link set usb0 up
+   # Wait for the new usb0 device and setup the IP address
+   TIMEOUT=30
+   while [ $TIMEOUT -gt 0 ]; do
+     if ip -6 addr flush dev usb0 && \
+        ip -6 addr add "fd66:66:66::1/64" dev usb0 && \
+        ip link set usb0 up; then
+         break
+     fi
+
+     sleep 0.5
+     TIMEOUT=$((TIMEOUT - 1))
+   done
+
+   if [ $TIMEOUT -le 0 ]; then
+     echo "Error: cannot configure usb0 after 30s"
+     exit 1
+   fi
 }
 
 dispose() {
